#!/bin/bash
# Unified Unit Test Server for All Viewer Components
# 全ビューアーコンポーネントの統合単体テストサーバー

echo "🧪 Starting Unified Unit Test Server for Viewer Components..."
echo "📁 Server directory: $(pwd)"
echo ""
echo "🎯 Available Unit Test URLs:"
echo "   ┌─ 🎵 Audio Reactive System:"
echo "   │   http://localhost:8002/shared-viewer-components/test-audio-reactive-system.html"
echo "   ├─ 📷 Camera Controls:"
echo "   │   http://localhost:8002/shared-viewer-components/test-camera-controls.html"
echo "   ├─ 🖱️ Mouse Interaction:"
echo "   │   http://localhost:8002/shared-viewer-components/test-mouse-interaction.html"
echo "   ├─ ⚡ Particle Effects:"
echo "   │   http://localhost:8002/shared-viewer-components/test-particle-effects.html"
echo "   ├─ 🎮 UI Controls:"
echo "   │   http://localhost:8002/shared-viewer-components/test-ui-controls.html"
echo "   └─ 🌐 Panorama Script:"
echo "       http://localhost:8002/threejs-panorama-viewer/test-panorama-unit.html"
echo ""
echo "🎯 Integration Test URLs:"
echo "   ├─ 📊 Point Cloud Viewer (Integrated):"
echo "   │   http://localhost:8002/threejs-pointcloud-viewer/test-refactored-viewer.html"
echo "   └─ 🌐 Panorama Viewer (Integrated):"
echo "       http://localhost:8002/threejs-panorama-viewer/test-panorama-viewer.html"
echo ""
echo "📝 Unit Test Instructions:"
echo "   1. 🎵 Audio Tests: Test Web Audio API, microphone, frequency analysis"
echo "   2. 📷 Camera Tests: Test Three.js camera, OrbitControls, positioning"
echo "   3. 🖱️ Mouse Tests: Test gravity effects, mouse trails, interaction modes"
echo "   4. ⚡ Particle Tests: Test depth effects, color mapping, GPU optimization"
echo "   5. 🎮 UI Tests: Test auto-hide panels, keyboard shortcuts, responsive design"
echo "   6. 🌐 Panorama Tests: Test spherical distribution, image analysis, 360° viewing"
echo ""
echo "✅ Integration Test Instructions:"
echo "   1. Test all components working together in real viewers"
echo "   2. Verify shared component integration and communication"
echo "   3. Confirm performance with full feature set"
echo "   4. Validate user experience across all functionality"
echo ""
echo "🔍 Testing Methodology:"
echo "   • Unit Tests: Individual component functionality verification"
echo "   • Integration Tests: Full system interaction and performance"
echo "   • Manual Tests: User interaction and visual verification"
echo "   • Automated Tests: Function existence and basic operation"
echo ""
echo "⏹️  Press Ctrl+C to stop the server"
echo ""

# Start Python HTTP server on port 8002 (dedicated for unit tests)
python3 -m http.server 8002