name: 'Three.js Integration & Packaging'
description: 'Integrate and package Three.js experience for distribution'
author: 'KamuiCode Workflow'

inputs:
  experience-concept:
    description: 'The 3D experience concept'
    required: true
  include-music:
    description: 'Whether music was included'
    required: false
    default: 'false'
  folder-name:
    description: 'The folder name containing Three.js files'
    required: true
  branch-name:
    description: 'The branch to work on'
    required: true
  oauth-token:
    description: 'Claude Code OAuth token'
    required: true

outputs:
  integration-completed:
    description: 'Whether integration was completed successfully'
    value: ${{ steps.integration.outputs.completed }}
  final-package-path:
    description: 'Path to the final package'
    value: ${{ steps.integration.outputs.final-package-path }}
  package-size:
    description: 'Size of the final package'
    value: ${{ steps.integration.outputs.package-size }}

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch-name }}
    
    - name: Download Three.js files artifact
      uses: actions/download-artifact@v4
      with:
        name: threejs-files-${{ inputs.folder-name }}
        path: .
    
    - name: Debug artifact download
      shell: bash
      run: |
        echo "🔧 デバッグ: アーティファクトダウンロード後のファイル構造確認"
        echo "Current working directory: $(pwd)"
        echo "Directory contents:"
        ls -la
        echo "Looking for folder: ${{ inputs.folder-name }}"
        if [ -d "${{ inputs.folder-name }}" ]; then
          echo "✅ フォルダが見つかりました"
          ls -la "${{ inputs.folder-name }}/"
          if [ -d "${{ inputs.folder-name }}/src" ]; then
            echo "✅ srcディレクトリが見つかりました"
            ls -la "${{ inputs.folder-name }}/src/"
          else
            echo "❌ srcディレクトリが見つかりません"
          fi
        else
          echo "❌ メインフォルダが見つかりません"
          echo "利用可能なディレクトリ:"
          find . -type d -name "*threejs*" -o -name "*experience*" 2>/dev/null || echo "該当するディレクトリなし"
        fi
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install Claude Code SDK
      shell: bash
      run: npm install @anthropic-ai/claude-code
    
    - name: Three.js Integration & Packaging Agent
      id: integration
      shell: bash
      env:
        CLAUDE_CODE_OAUTH_TOKEN: ${{ inputs.oauth-token }}
        EXPERIENCE_CONCEPT: ${{ inputs.experience-concept }}
        INCLUDE_MUSIC: ${{ inputs.include-music }}
        FOLDER_NAME: ${{ inputs.folder-name }}
      run: $GITHUB_WORKSPACE/.github/scripts/integrate-threejs-experience.sh
    
    - name: Setup docs folder for GitHub Pages
      shell: bash
      run: |
        echo "::group::📁 Setup docs folder"
        
        FOLDER_NAME="${{ inputs.folder-name }}"
        DOCS_DIR="docs/$FOLDER_NAME"
        
        # docs/フォルダ構造を作成
        mkdir -p "$DOCS_DIR"
        
        # src/index.htmlをdocs配下にコピー
        if [ -f "$FOLDER_NAME/src/index.html" ]; then
          cp "$FOLDER_NAME/src/index.html" "$DOCS_DIR/"
          echo "✅ Copied index.html to docs"
        fi
        
        # パノラマ画像をコピー
        if [ -f "$FOLDER_NAME/src/panorama.jpg" ]; then
          cp "$FOLDER_NAME/src/panorama.jpg" "$DOCS_DIR/"
          echo "✅ Copied panorama.jpg to docs"
        fi
        
        # 音楽ファイルがあればコピー
        if [ -f "$FOLDER_NAME/src/generated-music.wav" ]; then
          cp "$FOLDER_NAME/src/generated-music.wav" "$DOCS_DIR/"
          echo "✅ Copied music file to docs"
        fi
        
        # GitHub Pages用のindex.htmlがなければ作成
        if [ ! -f "docs/index.html" ]; then
          cat > docs/index.html << 'EOF'
        <!DOCTYPE html>
        <html>
        <head>
          <title>KamuiCode Three.js Experiences</title>
          <style>
            body { font-family: Arial, sans-serif; margin: 40px; }
            .experience { margin: 20px 0; padding: 20px; border: 1px solid #ddd; border-radius: 8px; }
            .experience h2 { margin-top: 0; }
            .experience a { color: #0066cc; text-decoration: none; }
            .experience a:hover { text-decoration: underline; }
          </style>
        </head>
        <body>
          <h1>🎯 KamuiCode Three.js Experiences</h1>
          <p>Generated 3D experiences with panorama backgrounds and particle effects.</p>
          <div id="experiences">
            <!-- Experiences will be listed here -->
          </div>
        </body>
        </html>
        EOF
          echo "✅ Created main docs/index.html"
        fi
        
        echo "::endgroup::"
    
    - name: Commit and push integration files
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
        # フォルダとdocsディレクトリを追加
        git add ${{ inputs.folder-name }}/
        git add docs/
        
        if git diff --cached --quiet; then
          echo "No integration files to commit"
        else
          git commit -m "Add final Three.js experience package: ${{ inputs.experience-concept }}"
          git push origin ${{ inputs.branch-name }}
        fi
        
        # mainブランチにdocs/をプッシュ
        echo "::group::📤 Push docs to main branch"
        
        # 現在のブランチを保存
        CURRENT_BRANCH=$(git branch --show-current)
        echo "Current branch: $CURRENT_BRANCH"
        
        # mainブランチの最新を取得
        git fetch origin main
        
        # mainブランチにチェックアウト
        git checkout main
        git pull origin main
        
        # feature branchからdocs/フォルダをコピー
        git checkout $CURRENT_BRANCH -- docs/
        
        # docs/フォルダをコミット
        if git diff --cached --quiet; then
          echo "No docs changes to commit to main"
        else
          git commit -m "Update GitHub Pages content: ${{ inputs.experience-concept }} [branch: ${{ inputs.branch-name }}, folder: ${{ inputs.folder-name }}]"
          git push origin main
        fi
        
        # 元のブランチに戻る
        git checkout $CURRENT_BRANCH
        echo "::endgroup::"

    
    - name: Setup docs folder for GitHub Pages
      shell: bash
      run: |
        echo "::group::📁 Setup docs folder"
        
        FOLDER_NAME="${{ inputs.folder-name }}"
        DOCS_DIR="docs/$FOLDER_NAME"
        
        # docs/フォルダ構造を作成
        mkdir -p "$DOCS_DIR"
        
        # src/index.htmlをdocs配下にコピー
        if [ -f "$FOLDER_NAME/src/index.html" ]; then
          cp "$FOLDER_NAME/src/index.html" "$DOCS_DIR/"
          echo "✅ Copied index.html to docs"
        fi
        
        # パノラマ画像をコピー
        if [ -f "$FOLDER_NAME/src/panorama.jpg" ]; then
          cp "$FOLDER_NAME/src/panorama.jpg" "$DOCS_DIR/"
          echo "✅ Copied panorama.jpg to docs"
        fi
        
        # 音楽ファイルがあればコピー
        if [ -f "$FOLDER_NAME/src/generated-music.wav" ]; then
          cp "$FOLDER_NAME/src/generated-music.wav" "$DOCS_DIR/"
          echo "✅ Copied music file to docs"
        fi
        
        # GitHub Pages用のindex.htmlがなければ作成
        if [ ! -f "docs/index.html" ]; then
          cat > docs/index.html << 'EOF'
        <!DOCTYPE html>
        <html>
        <head>
          <title>KamuiCode Three.js Experiences</title>
          <style>
            body { font-family: Arial, sans-serif; margin: 40px; }
            .experience { margin: 20px 0; padding: 20px; border: 1px solid #ddd; border-radius: 8px; }
            .experience h2 { margin-top: 0; }
            .experience a { color: #0066cc; text-decoration: none; }
            .experience a:hover { text-decoration: underline; }
          </style>
        </head>
        <body>
          <h1>🎯 KamuiCode Three.js Experiences</h1>
          <p>Generated 3D experiences with panorama backgrounds and particle effects.</p>
          <div id="experiences">
            <!-- Experiences will be listed here -->
          </div>
        </body>
        </html>
        EOF
          echo "✅ Created main docs/index.html"
        fi
        
        echo "::endgroup::"
    
    - name: Commit and push integration files
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
        # フォルダとdocsディレクトリを追加
        git add ${{ inputs.folder-name }}/
        git add docs/
        
        if git diff --cached --quiet; then
          echo "No integration files to commit"
        else
          git commit -m "Add final Three.js experience package: ${{ inputs.experience-concept }}"
          git push origin ${{ inputs.branch-name }}
        fi
        
        # mainブランチにdocs/をプッシュ
        echo "::group::📤 Push docs to main branch"
        
        # 現在のブランチを保存
        CURRENT_BRANCH=$(git branch --show-current)
        echo "Current branch: $CURRENT_BRANCH"
        
        # mainブランチの最新を取得
        git fetch origin main
        
        # mainブランチにチェックアウト
        git checkout main
        git pull origin main
        
        # feature branchからdocs/フォルダをコピー
        git checkout $CURRENT_BRANCH -- docs/
        
        # docs/フォルダをコミット
        if git diff --cached --quiet; then
          echo "No docs changes to commit to main"
        else
          git commit -m "Update GitHub Pages content: ${{ inputs.experience-concept }} [branch: ${{ inputs.branch-name }}, folder: ${{ inputs.folder-name }}]"
          git push origin main
        fi
        
        # 元のブランチに戻る
        git checkout $CURRENT_BRANCH
        echo "::endgroup::"