name: '360° Panorama Viewer'
description: 'Creates a 360-degree panoramic particle viewer using Three.js with shared components'
inputs:
  input_image:
    description: 'Input image file for panoramic display'
    required: true
  output_filename:
    description: 'Output filename for the panorama viewer'
    required: false
    default: 'panorama-viewer.html'
  background_color:
    description: 'Background color for the panorama viewer (hex format)'
    required: false
    default: '#000814'
  camera_position_radius:
    description: 'Initial camera position radius from center'
    required: false
    default: '100'
  particle_density:
    description: 'Particle density for panoramic display (low/medium/high)'
    required: false
    default: 'medium'
  auto_rotate:
    description: 'Enable auto-rotation'
    required: false
    default: 'true'
  rotation_speed:
    description: 'Auto-rotation speed'
    required: false
    default: '1.0'
  enable_music:
    description: 'Enable music integration'
    required: false
    default: 'false'
  music_file:
    description: 'Music file for audio-reactive effects'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Setup panorama viewer environment
      shell: bash
      run: |
        echo "🌐 Setting up 360° Panorama Viewer environment..."
        echo "Input image: ${{ inputs.input_image }}"
        echo "Output filename: ${{ inputs.output_filename }}"
        echo "Background color: ${{ inputs.background_color }}"
        echo "Particle density: ${{ inputs.particle_density }}"
        
    - name: Process input image for panoramic display
      shell: bash
      run: |
        echo "🖼️ Processing image for panoramic display..."
        # Create assets directory
        mkdir -p assets
        
        # Copy input image to assets
        if [ -f "${{ inputs.input_image }}" ]; then
          cp "${{ inputs.input_image }}" assets/panorama-image.jpg
          echo "✅ Image copied to assets/panorama-image.jpg"
        else
          echo "❌ Input image not found: ${{ inputs.input_image }}"
          exit 1
        fi
        
    - name: Create panorama viewer from template
      shell: bash
      run: |
        echo "🎨 Creating panorama viewer from template..."
        
        # Copy template and replace placeholders
        cp ${{ github.action_path }}/panorama-template.html ${{ inputs.output_filename }}
        
        # Replace placeholders in the HTML file
        sed -i '' "s/BACKGROUND_COLOR_PLACEHOLDER/${{ inputs.background_color }}/g" ${{ inputs.output_filename }}
        sed -i '' "s/CAM_RADIUS_PLACEHOLDER/${{ inputs.camera_position_radius }}/g" ${{ inputs.output_filename }}
        sed -i '' "s/PARTICLE_DENSITY_PLACEHOLDER/${{ inputs.particle_density }}/g" ${{ inputs.output_filename }}
        sed -i '' "s/AUTO_ROTATE_PLACEHOLDER/${{ inputs.auto_rotate }}/g" ${{ inputs.output_filename }}
        sed -i '' "s/ROTATION_SPEED_PLACEHOLDER/${{ inputs.rotation_speed }}/g" ${{ inputs.output_filename }}
        
        # Handle music integration
        if [ "${{ inputs.enable_music }}" = "true" ] && [ -n "${{ inputs.music_file }}" ]; then
          echo "🎵 Enabling music integration..."
          sed -i '' "s/MUSIC_INIT_PLACEHOLDER/setupMusic();/g" ${{ inputs.output_filename }}
          sed -i '' "s/MUSIC_FILE_PLACEHOLDER/${{ inputs.music_file }}/g" ${{ inputs.output_filename }}
          # Add music functions placeholder
          MUSIC_FUNCTIONS='function setupMusic() { console.log("🎵 Music system initialized for panorama viewer"); }'
          sed -i '' "s/MUSIC_FUNCTIONS_PLACEHOLDER/$MUSIC_FUNCTIONS/g" ${{ inputs.output_filename }}
          sed -i '' "s/MUSIC_WINDOW_PLACEHOLDER/window.setupMusic = setupMusic;/g" ${{ inputs.output_filename }}
        else
          echo "🔇 Music integration disabled"
          sed -i '' "s/MUSIC_INIT_PLACEHOLDER//g" ${{ inputs.output_filename }}
          sed -i '' "s/MUSIC_FUNCTIONS_PLACEHOLDER//g" ${{ inputs.output_filename }}
          sed -i '' "s/MUSIC_WINDOW_PLACEHOLDER//g" ${{ inputs.output_filename }}
        fi
        
        # Copy panorama script
        cp ${{ github.action_path }}/panorama-script.js panorama-script.js
        
        echo "✅ Panorama viewer created: ${{ inputs.output_filename }}"
        
    - name: Validate panorama viewer
      shell: bash
      run: |
        echo "✅ Validating panorama viewer..."
        
        # Check if files exist
        if [ ! -f "${{ inputs.output_filename }}" ]; then
          echo "❌ Output file not found"
          exit 1
        fi
        
        if [ ! -f "panorama-script.js" ]; then
          echo "❌ Panorama script not found"
          exit 1
        fi
        
        if [ ! -f "assets/panorama-image.jpg" ]; then
          echo "❌ Panorama image not found"
          exit 1
        fi
        
        echo "🌟 360° Panorama Viewer created successfully!"
        echo "📄 Output file: ${{ inputs.output_filename }}"
        echo "🖼️ Panorama image: assets/panorama-image.jpg"
        echo "📜 Script file: panorama-script.js"