name: 'Three.js Scene Generation'
description: 'Generate Three.js 3D scenes with panorama and particles using Three.js MCP'
author: 'KamuiCode Workflow'

inputs:
  experience-concept:
    description: 'The 3D experience concept'
    required: true
  panorama-image-url:
    description: 'Google URL of the panorama image'
    required: false
  background-type:
    description: 'Background type (panorama/solid_black/solid_white/transparent/gradient)'
    required: false
    default: 'panorama'
  visual-type:
    description: 'Visual type (particle_art/simple_particles)'
    required: false
    default: 'particle_art'
  particle-art-category:
    description: 'Particle art category (flower/nature/geometric/abstract)'
    required: false
    default: 'flower'
  flower-type:
    description: 'Type of flower (sakura/rose/lily/tulip/mixed)'
    required: false
    default: 'sakura'
  nature-type:
    description: 'Type of nature element (tree/ocean/mountain/forest/mixed)'
    required: false
    default: 'tree'
  geometric-type:
    description: 'Type of geometric shape (sphere/cube/pyramid/torus/mixed)'
    required: false
    default: 'sphere'
  abstract-type:
    description: 'Type of abstract form (fluid/crystalline/organic/fractal/mixed)'
    required: false
    default: 'fluid'
  arrangement:
    description: 'Arrangement style (floating/grounded/scene)'
    required: false
    default: 'floating'
  color-scheme:
    description: 'Color scheme (auto/warm/cool/monochrome/vibrant/pastel)'
    required: false
    default: 'auto'
  effects:
    description: 'Additional effects (none/sparkle/glow/trail/shimmer/multiple)'
    required: false
    default: 'none'
  effect-particle-shape:
    description: 'Effect particle shape (circle/star/diamond/heart/custom)'
    required: false
    default: 'circle'
  include-music:
    description: 'Whether to include music controls'
    required: false
    default: 'false'
  music-url:
    description: 'Google URL of the background music (if applicable)'
    required: false
  particle-count:
    description: 'Number of particles (500/1000/2000/5000)'
    required: false
    default: '1000'
  folder-name:
    description: 'The folder name for storing Three.js files'
    required: true
  branch-name:
    description: 'The branch to work on'
    required: true
  oauth-token:
    description: 'Claude Code OAuth token'
    required: true

outputs:
  threejs-completed:
    description: 'Whether Three.js scene generation was completed successfully'
    value: ${{ steps.threejs.outputs.completed }}
  scene-files-created:
    description: 'Number of scene files created'
    value: ${{ steps.threejs.outputs.scene-files-created }}

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch-name }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install Claude Code SDK
      shell: bash
      run: npm install @anthropic-ai/claude-code
    
    - name: Three.js Scene Generation Agent
      id: threejs
      shell: bash
      env:
        CLAUDE_CODE_OAUTH_TOKEN: ${{ inputs.oauth-token }}
        FOLDER_NAME: ${{ inputs.folder-name }}
        EXPERIENCE_CONCEPT: ${{ inputs.experience-concept }}
        PANORAMA_IMAGE_URL: ${{ inputs.panorama-image-url }}
        BACKGROUND_TYPE: ${{ inputs.background-type }}
        VISUAL_TYPE: ${{ inputs.visual-type }}
        PARTICLE_ART_CATEGORY: ${{ inputs.particle-art-category }}
        FLOWER_TYPE: ${{ inputs.flower-type }}
        NATURE_TYPE: ${{ inputs.nature-type }}
        GEOMETRIC_TYPE: ${{ inputs.geometric-type }}
        ABSTRACT_TYPE: ${{ inputs.abstract-type }}
        ARRANGEMENT: ${{ inputs.arrangement }}
        COLOR_SCHEME: ${{ inputs.color-scheme }}
        EFFECTS: ${{ inputs.effects }}
        EFFECT_PARTICLE_SHAPE: ${{ inputs.effect-particle-shape }}
        INCLUDE_MUSIC: ${{ inputs.include-music }}
        MUSIC_URL: ${{ inputs.music-url }}
        PARTICLE_COUNT: ${{ inputs.particle-count }}
      run: $GITHUB_WORKSPACE/.github/scripts/generate-threejs-scene.sh
    
    - name: Upload Three.js files as artifact
      uses: actions/upload-artifact@v4
      with:
        name: threejs-files-${{ inputs.folder-name }}
        path: ${{ inputs.folder-name }}/
        retention-days: 1
    
    - name: Commit and push Three.js files
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add ${{ inputs.folder-name }}/
        git add .github/scripts/generate-threejs-scene.sh
        if git diff --cached --quiet; then
          echo "No Three.js files to commit"
        else
          git commit -m "Add Three.js scene: ${{ inputs.experience-concept }}"
          git push origin ${{ inputs.branch-name }}
        fi
