name: 'Three.js Scene Generation'
description: 'Generate Three.js 3D scenes with panorama and particles using Three.js MCP'
author: 'KamuiCode Workflow'

inputs:
  experience-concept:
    description: 'The 3D experience concept'
    required: true
  panorama-image-url:
    description: 'Google URL of the panorama image'
    required: false
  background-type:
    description: 'Background type (panorama/solid_black/solid_white/transparent/gradient)'
    required: false
    default: 'panorama'
  art-mode:
    description: 'Art creation mode (none/sculptural/organic/geometric/abstract)'
    required: false
    default: 'none'
  art-object-type:
    description: 'Type of 3D art object to create'
    required: false
  complexity-level:
    description: 'Complexity level (simple/medium/complex/masterpiece)'
    required: false
    default: 'medium'
  include-music:
    description: 'Whether to include music controls'
    required: false
    default: 'false'
  music-url:
    description: 'Google URL of the background music (if applicable)'
    required: false
  particle-enabled:
    description: 'Whether to enable particle effects'
    required: false
    default: 'true'
  particle-config:
    description: 'Particle configuration (count:size:shape:corner_radius)'
    required: false
    default: '1000:0.5:circle:0.0'
  folder-name:
    description: 'The folder name for storing Three.js files'
    required: true
  branch-name:
    description: 'The branch to work on'
    required: true
  oauth-token:
    description: 'Claude Code OAuth token'
    required: true

outputs:
  threejs-completed:
    description: 'Whether Three.js scene generation was completed successfully'
    value: ${{ steps.threejs.outputs.completed }}
  scene-files-created:
    description: 'Number of scene files created'
    value: ${{ steps.threejs.outputs.scene-files-created }}

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch-name }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install Claude Code SDK
      shell: bash
      run: npm install @anthropic-ai/claude-code
    
    - name: Three.js Scene Generation Agent
      id: threejs
      shell: bash
      env:
        CLAUDE_CODE_OAUTH_TOKEN: ${{ inputs.oauth-token }}
        FOLDER_NAME: ${{ inputs.folder-name }}
      run: ${{ github.action_path }}/../../scripts/generate-threejs-scene.sh
    
    - name: Upload Three.js files as artifact
      uses: actions/upload-artifact@v4
      with:
        name: threejs-files-${{ inputs.folder-name }}
        path: ${{ inputs.folder-name }}/
        retention-days: 1
    
    - name: Commit and push Three.js files
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add ${{ inputs.folder-name }}/
        git add .github/scripts/generate-threejs-scene.sh
        if git diff --cached --quiet; then
          echo "No Three.js files to commit"
        else
          git commit -m "Add Three.js scene: ${{ inputs.experience-concept }}"
          git push origin ${{ inputs.branch-name }}
        fi
