name: Debug OAuth Authentication

on:
  workflow_dispatch:

jobs:
  debug-oauth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install Claude Code SDK
        run: npm install @anthropic-ai/claude-code
      
      - name: Test CLAUDE_USE_SUBSCRIPTION
        env:
          CLAUDE_USE_SUBSCRIPTION: "true"
        run: |
          echo "=== Environment Variables Check ==="
          echo "CLAUDE_USE_SUBSCRIPTION: $CLAUDE_USE_SUBSCRIPTION"
          
          echo "=== Claude CLI Version ==="
          npx @anthropic-ai/claude-code --version
          
          echo "=== Claude CLI Help ==="
          npx @anthropic-ai/claude-code --help | head -20
          
          echo "=== Test Simple Claude CLI Call ==="
          echo "Testing with minimal prompt..."
          npx @anthropic-ai/claude-code --print -p "Hello, respond with just 'Hello back'" || echo "CLI call failed"