name: Debug OAuth Authentication

on:
  workflow_dispatch:

jobs:
  debug-oauth:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install Claude Code SDK
        run: npm install @anthropic-ai/claude-code
      
      - name: Test Method 1 - OAuth Config File Creation
        env:
          CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
        run: |
          echo "=== Method 1: OAuth Config File Creation ==="
          
          # Create Claude config directory
          mkdir -p ~/.claude
          
          # Test with CLAUDE_CODE_OAUTH_TOKEN environment variable
          echo "CLAUDE_CODE_OAUTH_TOKEN set: ${CLAUDE_CODE_OAUTH_TOKEN:+YES}"
          echo "Token prefix: ${CLAUDE_CODE_OAUTH_TOKEN:0:20}..."
          
          echo "=== Testing Prompt Variable Construction ==="
          
          # Test variables like in the actual workflow
          FINAL_IMAGE_PROMPT="A beautiful red rose with detailed petals"
          
          # Test prompt construction with English (like successful users might use)
          PROMPT="Generate image segment 1.

          **Image prompt**: $FINAL_IMAGE_PROMPT

          **Steps**:
          1. Use the image prompt ($FINAL_IMAGE_PROMPT) to generate image with Imagen4 Fast
          2. Use mcp__t2i-fal-imagen4-fast__imagen4_fast_submit tool"
          
          echo "=== Debug Output ==="
          echo "FINAL_IMAGE_PROMPT: '$FINAL_IMAGE_PROMPT'"
          echo "PROMPT length: ${#PROMPT}"
          echo "PROMPT content:"
          echo "$PROMPT"
          echo "=== End Debug ==="
          
          echo "=== Testing Claude CLI with constructed prompt ==="
          npx @anthropic-ai/claude-code --print -p "$PROMPT" || echo "Prompt construction test failed"
      
      - name: Test Method 2 - grll/claude-code-action
        uses: grll/claude-code-action@beta
        with:
          use_oauth: true
          claude_access_token: ${{ secrets.CLAUDE_ACCESS_TOKEN }}
          claude_refresh_token: ${{ secrets.CLAUDE_REFRESH_TOKEN }}
          claude_expires_at: ${{ secrets.CLAUDE_EXPIRES_AT }}
          prompt: "Hello, respond with just 'Test 2 success'"
          allowedTools: "Read,Write"
          max-turns: 1
          verbose: true