name: Debug OAuth Authentication

on:
  workflow_dispatch:

jobs:
  debug-oauth:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install Claude Code SDK
        run: npm install @anthropic-ai/claude-code
      
      - name: Test Method 1 - OAuth Config File Creation
        env:
          CLAUDE_ACCESS_TOKEN: ${{ secrets.CLAUDE_ACCESS_TOKEN }}
          CLAUDE_REFRESH_TOKEN: ${{ secrets.CLAUDE_REFRESH_TOKEN }}
          CLAUDE_EXPIRES_AT: ${{ secrets.CLAUDE_EXPIRES_AT }}
        run: |
          echo "=== Method 1: OAuth Config File Creation ==="
          
          # Create Claude config directory
          mkdir -p ~/.claude
          
          # Create OAuth token file with GitHub secrets
          cat > ~/.claude/oauth_token.json << EOF
          {
            "access_token": "$CLAUDE_ACCESS_TOKEN",
            "refresh_token": "$CLAUDE_REFRESH_TOKEN",
            "expires_at": "$CLAUDE_EXPIRES_AT",
            "token_type": "bearer"
          }
          EOF
          
          echo "OAuth config file created"
          echo "File contents (masked):"
          echo "access_token: ${CLAUDE_ACCESS_TOKEN:0:10}..."
          echo "refresh_token: ${CLAUDE_REFRESH_TOKEN:0:10}..."
          echo "expires_at: $CLAUDE_EXPIRES_AT"
          
          echo "=== Testing Claude CLI with OAuth file ==="
          npx @anthropic-ai/claude-code --print -p "Hello, respond with just 'Test 1 success'" || echo "Method 1 failed"
      
      - name: Test Method 2 - grll/claude-code-action
        uses: grll/claude-code-action@beta
        with:
          use_oauth: true
          claude_access_token: ${{ secrets.CLAUDE_ACCESS_TOKEN }}
          claude_refresh_token: ${{ secrets.CLAUDE_REFRESH_TOKEN }}
          claude_expires_at: ${{ secrets.CLAUDE_EXPIRES_AT }}
          prompt: "Hello, respond with just 'Test 2 success'"
          allowedTools: "Read,Write"
          max-turns: 1
          verbose: true