
name: Gemini CLI Test

on:
  workflow_dispatch:

jobs:
  test-gemini:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Run Gemini CLI Action
        uses: google-gemini/gemini-cli-action@v0
        with:
          api-key: ${{ secrets.GEMINI_API_KEY }}
          command: "gemini-cli --prompt 'Hello, Gemini! How are you today?'"
